### PR TITLE
Fix disable editing buttons

### PR DESCRIPTION
**Pull request by mar-be**
This PR removes the buttons to edit the markdown of patterns if editing is switched off in the configuration.

### CODE REVIEW

**Comment by mar-be** [comment]
Related to https://github.com/PatternAtlas/pattern-atlas-ui/issues/96 but it implements only a subset of the features

**Review by lharzenetter — COMMENTED** [review]
LGTM, maybe also add a default if the config server is not there or not reachable --> always set the readonly mode?

**Comment by mar-be** [comment]
@lharzenetter The default configuration values which are used if the config server is not reachable are all set to true:
https://github.com/PatternAtlas/pattern-atlas-ui/blob/57b37d6a5608905d529453aaa8f75b371d44551d/src/app/core/directives/pattern-atlas-ui-repository-configuration.service.ts#L41

**Comment by lharzenetter** [comment]
Hmm, I guess should make this false, what do you think?

**Review by lharzenetter — APPROVED** [review]
LGTM

**Pull request merged**
